<a href="https://colab.research.google.com/github/Basilisa1008/Pytorch-Beginner/blob/main/Tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Tensor Operation***

In [1]:
import torch

***arange()*** : ***it generates a sequence*** (A digital counter where you control), a sequence in a sense that basically a sequence of numbers with specific start, end, and step values (similar to counting but with more control)
                Syntax : ***arange(start,end,step)***
 - Where to start counting
 - Where to stop counting
 - How much to increment each time

In [3]:
#creates a 1-dimensional tensor containing numbers from 0 to 9:
torch_1 = torch.arange(10)
torch_1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***Reshape***
- Preserves all the original values.
- It changes only how they're arranged.
- It must maintain the same total number of elements (in this case, 2 × 5 = 10)
- Fills the new shape row by row from left to right

***Question: Why reshape(2,3) failed ?***

 ***Answer***
  - The key rule with reshape is that the total number of elements must stay the same. In your case:
 - Original tensor has 10 elements where for 2×3 matrix would have 2 × 3 = 6 elements hence this is impossible because you can't fit 10 elements into 6 spaces
 - It's like trying to pour 10 ounces of water into a 6-ounce container - it simply won't fit!

In [6]:
# How to rechape using reshape and view
#reorganizes these 10 numbers into a 2×5 matrix
torch_1 = torch_1.reshape(2,5)
torch_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

***Remember this ***: The **-1** is like telling PyTorch: ***"You figure out what this dimension should be to make everything fit."***
- It's particularly useful when you:
  - Don't know the exact size of your tensor
  - Want to flatten a tensor (convert to 1D)
  - Want to reshape while keeping one dimension fixed

In [7]:
# Reshaping when we are not aware of number of elements dealt with using -1
torch_1 = torch_1.reshape(2,-1)
torch_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
torch_1 = torch_1.reshape(-1,5)
torch_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

***view()***
- It only works with contiguous tensors
- It shares memory with the original tensor
- It's generally faster than reshape (when it works)
- Changes to the view affect the original tensor

In [9]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
x = x.view(3,-1)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Differences between reshape() and view()
- Memory Continuity
- Sharing Memory


***Use when***
- Use view() when you know your tensor is contiguous and want to ensure memory sharing
- Use reshape() when you're unsure about tensor continuity or don't need memory sharing

***Point to take (Contigous Vs Non-Contiguous)***
- A tensor is considered*** "contiguous" ***when its elements are stored in memory in a continuous, unbroken sequence. This means that the elements are laid out one after the other, without any gaps or empty spaces between them.
- A ***"non-contiguous"*** tensor, on the other hand, is a tensor where the elements are not stored in a continuous sequence in memory. This could happen if you, for example, take a 2D tensor and transpose it (swap the rows and columns), or if you select a subset of the elements from a tensor.
     - Example the tensor was [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     we take the even numbers out it turns into [1,3,5,7,9,11,15]- non contigous tensor since it has gaps in it

In [15]:
# Memory continuity
y = torch.arange(12).reshape(3,4)
y_nonconti = y.transpose(0,1) # make the tensor non-contigous

reshaped_y = y_nonconti.reshape(-1,3)

reshaped_y

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [16]:
reshaped_y = y_nonconti.view(3,-1)
reshaped_y

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [3]:
import torch

In [4]:
# with reshape and view it will update the tensor
z_tensor = torch.arange(15)
z_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
z_tensor = z_tensor.reshape(-1,5)
z_tensor

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [10]:
# If you want to access elements in a 2D tensor, you need two indices:
# z_tensor[row_index, column_index]

# To access element 9 you would use:
z_tensor[1, 4]  # Second row (index 1), fifth column (index 4)

# To set a value:
z_tensor[1, 4] = 444
z_tensor

tensor([[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8, 444],
        [ 10,  11,  12,  13,  14]])

In [11]:
z1_tensor = z_tensor.reshape(5,3)
z1_tensor

tensor([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [444,  10,  11],
        [ 12,  13,  14]])

In [12]:
z1_tensor [2, 1] = 55
z1_tensor

tensor([[  0,   1,   2],
        [  3,   4,   5],
        [  6,  55,   8],
        [444,  10,  11],
        [ 12,  13,  14]])

In [13]:
# notice the number 7 is changed to 55 on z1_tensor and the chages were also propagated to z_tensor
#hence with reshape and view it will update the tensor
z_tensor

tensor([[  0,   1,   2,   3,   4],
        [  5,   6,  55,   8, 444],
        [ 10,  11,  12,  13,  14]])

***Slicing***

The basic syntax : tensor[start:stop:step], where:

- start: starting index (inclusive)
- stop: ending index (exclusive)
- step: how many items to skip between elements

In [14]:
t = torch.arange(10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
t = t.reshape(2,-1)
t

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# Grab a slice
t[0, :]

tensor([0, 1, 2, 3, 4])

In [22]:
t = t[2:5]      # From index 2 to 4: [2,3,4]
t

tensor([], size=(0, 5), dtype=torch.int64)