<a href="https://colab.research.google.com/github/Basilisa1008/Pytorch-Beginner/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors** - simply as numpy array or python list, Just like how in Machine learning you use numpy array to store things in Deep Learning it makes use of Tensors

- They’re built to shine on GPUs, making deep learning super fast. 💡 apart from that **Tensors** are multi-dimensional matrix that contains elements of a single data type

- The defauly data type for Tensors is Float32

- Key feature: They enable automatic differentiation, which powers backpropagation in neural networks.

In [1]:
import torch

In [2]:
import numpy as np

***Lists***

In [5]:
the_list = [[44,55,77,88,33,22,11], [11,22,33,88,77,55,44]]
the_list

[[44, 55, 77, 88, 33, 22, 11], [11, 22, 33, 88, 77, 55, 44]]

***Numpy Array***

In [6]:
dimension = np.random.rand(3,2)
dimension

array([[0.90667046, 0.42166114],
       [0.86968087, 0.72588331],
       [0.33973685, 0.74962237]])

***Tensors***

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.4297,  0.5853,  0.4231,  1.3476],
        [ 0.4919,  1.4127,  1.9528,  0.5884],
        [ 1.2640, -1.3731, -0.3627,  0.0682]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
# Creating a tensor out of numpy array
my_tensor = torch.tensor(dimension)
my_tensor

tensor([[0.9067, 0.4217],
        [0.8697, 0.7259],
        [0.3397, 0.7496]], dtype=torch.float64)