<a href="https://colab.research.google.com/github/Basilisa1008/Pytorch-Beginner/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Math Operations with Tensors !***

**Key Point to Remember here are:**

1. Basic Operations:

  - Use +, -, *, /   for element-wise operations
Use @ or torch.matmul() for matrix multiplication
torch.add(), torch.sub(), etc. are alternative syntax


2. Statistical Operations:

  - Most statistical operations require float tensors
Use dim parameter to specify operation direction
Common functions: mean(), sum(), std(), var()


3. Dimensional Operations:

  - dim=0 operates on columns
  - dim=1 operates on rows
  - Can use negative dimensions (-1 = last dimension)


4. Shape Manipulation:

 - reshape() changes tensor shape
 - t() transposes 2D tensors
  - permute() for more complex transpositions

In [3]:
import torch

In [6]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([20,40,60,80,100])

# two options
a + b   # option 1

c = torch.add(a,b)   # option 2
c

tensor([ 21,  42,  63,  84, 105])

In [7]:
a-b

tensor([-19, -38, -57, -76, -95])

In [8]:
d = torch.sub(a,b)
d

tensor([-19, -38, -57, -76, -95])

In [9]:
a*b

tensor([ 20,  80, 180, 320, 500])

In [11]:
e = torch.mul(a,b)
e

tensor([ 20,  80, 180, 320, 500])

In [12]:
a / b

tensor([0.0500, 0.0500, 0.0500, 0.0500, 0.0500])

In [13]:
f = torch.div(a,b)
f

tensor([0.0500, 0.0500, 0.0500, 0.0500, 0.0500])

In [15]:
 b % a

tensor([0, 0, 0, 0, 0])

In [17]:
g = torch.remainder(b,a)
g

tensor([0, 0, 0, 0, 0])

In [18]:
# exponents / power
tensor_a = torch.pow(b,a)
tensor_a

tensor([         20,        1600,      216000,    40960000, 10000000000])

In [19]:
# Other way to do the math operation
a.add(b)

tensor([ 21,  42,  63,  84, 105])

In [22]:
# Reassignment
 # a = a + b  , way 1 OR

 # Using the underscore sign
a.add_(b)

tensor([ 21,  42,  63,  84, 105])

In [23]:
a

tensor([ 21,  42,  63,  84, 105])